=head1 BlueCoat::SGOS

BlueCoat::SGOS - a module to parse the configuration from a Blue Coat SGOS
device.  It was formerly Net::BlueCoat::SGOS.

=head1 INSTALLATION

L<BlueCoat::SGOS> uses well-tested and widely-used CPAN modules, so 
installation should be as simple as:

=over

=item C<CPAN>

    cpan BlueCoat::SGOS

=item C<cpanminus>
    
    cpanm BlueCoat::SGOS


=item C<most Unix platforms>
    
    perl Makefile.PL
    make
    make test
    make install


=item C<The most portable option>

    perl Build.PL
    ./Build
    ./Build test
    ./Build install

=back

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc BlueCoat::SGOS

You can also look for information at:

=over

=item * L<RT, CPAN's request tracker|http://rt.cpan.org/NoAuth/Bugs.html?Dist=BlueCoat-SGOS>

=item * L<AnnoCPAN, Annotated CPAN documentation|http://annocpan.org/dist/BlueCoat-SGOS>

=item * L<CPAN Ratings|http://cpanratings.perl.org/d/BlueCoat-SGOS>

=item * L<CPAN Search|http://search.cpan.org/dist/BlueCoat-SGOS/>

=back


=head1 TODO

There are many things to do:

=over

=item * Stabilize the API

=item * Effectively extract the CPL and VPM-XML data

=back



=head2 B<WARNING >

This is currently beta-quality software.  This means:


=over

=item * there could be bugs

=item * the API is not stable

=back



It has been tested on a handful of sysinfo files with great
success.

Because sysinfo data is semi-unstructured, this module
reads everything into memory and splits it apart
at each "delimiter" section.  This is inefficient
and slow.


=head1 SOURCE

The source is located here: L<http://github.com/mmlange/perl-bluecoat/sgos>

The following is the status of the last build as reported by Travis CI:

=begin html

<p>
  <img src="https://travis-ci.org/mmlange/perl-bluecoat-sgos.svg?branch=master" alt="Travis CI build status">
</p>

=end html

=head1 AUTHOR

Matthew Lange E<lt>mmlange@cpan.orgE<gt>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2008-2015 Matthew Lange

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published
by the Free Software Foundation.

