=head1 BlueCoat::SGOS

BlueCoat::SGOS - a module to parse the configuration from a Blue Coat SGOS
device.

=head1 DESCRIPTION

L<BlueCoat::SGOS> is a module to parse the sysinfo from a Blue Coat SGOS
device.  It was formerly Net::BlueCoat::SGOS.

=head1 INSTALLATION

L<BlueCoat::SGOS> uses well-tested and widely-used CPAN modules, so 
installation should be as simple as:

=over

=item C<CPAN>

    $ cpan BlueCoat::SGOS

=item C<cpanminus>
    
    $ cpanm BlueCoat::SGOS

=item C<most Unix platforms>
    
    $ perl Makefile.PL
    $ make
    $ make test
    $ make install

=item C<The most portable option>

    $ perl Build.PL
    $ ./Build
    $ ./Build test
    $ ./Build install

=back








=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc BlueCoat::SGOS

You can also look for information at:

    RT, CPAN's request tracker
        http://rt.cpan.org/NoAuth/Bugs.html?Dist=BlueCoat-SGOS

    AnnoCPAN, Annotated CPAN documentation
        http://annocpan.org/dist/BlueCoat-SGOS

    CPAN Ratings
        http://cpanratings.perl.org/d/BlueCoat-SGOS

    Search CPAN
        http://search.cpan.org/dist/BlueCoat-SGOS/


=head1 TODO

There are many things to do:
* Stabilize the API
* Effectively extract the CPL and VPM-XML data

** WARNING 
This is currently beta-quality software.  This means:
+ there could be bugs
+ the API is not stable

It has been tested on a handful of sysinfo files with great
success.

Because sysinfo data is semi-unstructured, this module
reads everything into memory and splits it apart
at each "delimiter" section.  This is inefficient
and slow.


=head1 SOURCE

=begin html

L<http://github.com/mmlange/perl-bluecoat/sgos>

<p>
  <img src="https://travis-ci.org/mmlange/perl-bluecoat-sgos.svg?branch=master" alt="Travis CI build status">
</p>

=end html

=head1 AUTHOR

Matthew Lange E<lt>mmlange@cpan.org<gt>E

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2008-2015 Matthew Lange

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published
by the Free Software Foundation.

